### ISSUE TITLE
Provide ARM image

### ISSUE THREAD

**Issue by fjorgemota** [varnish/docker-varnish#12]
Hello.

First, thanks for the project. It's useful to have a Varnish docker image mostly ready for use. =)

Second, I would like to suggest to provide ARM docker images, similar to the already provided X86 docker images, but...for ARM. Various official docker images provide that support and, according to my research, Varnish seems to work fine on ARM too (at least according to [Travis CI](https://travis-ci.org/varnishcache/varnish-cache)) and the [debian base image](https://hub.docker.com/_/debian/) that this image uses also provides ARM images..

**Comment by fjorgemota** [comment]
This could be fixed  by creating a docker image based on Alpine, as suggested by #2, given that apparently packagecloud.io doesn't provide a ARM64 package for Varnish..but Alpine does.

Interesting. :thinking:

**Comment by gquintard** [comment]
Hi,

so, packages are created on `circleci` (https://circleci.com/gh/varnishcache/varnish-cache/tree/master), and are then pushed to `packagecloud` (https://packagecloud.io/varnishcache), and are then used here (https://github.com/varnish/docker-varnish/blob/master/fresh/debian/Dockerfile).

Note that this is all Varnish Cache / Varnish Software stuff. `alpine` does offer it's own packages, which are unrelated to the pipeline I described.

The main issue at the moment is that circleci doesn't offer a way to build on arm (last time I checked), severely limiting the package offer.

One approach is to "just" build the packages here, in the `Dockerfile`. It should only be a matter of:
- setting up a container like this https://github.com/varnishcache/varnish-cache/blob/master/.circleci/config.yml#L191
- grabbing the source  tarball and the right commit in https://github.com/varnishcache/pkg-varnish-cache
- build
- install the apk
- throw the junk away

PR welcome

**Comment by fjorgemota** [comment]
hmmm..I'm not sure how I could help with a PR for this...specially that we're still dependent on a ARM support on CircleCI to work on. The instructions you given, AFAIK, would apply to a Alpine image with Varnish official sources embedded, and I'm not sure there would be a way to do that without access to a ARM machine.

Maybe, and just maybe, could we try to use cross-compilation to get ARM executables and then test then using QEmu ARM? I'm sure there are some performance impact by the emulation but then we could just push the generated ARM packages to packagecloud and use it here instead. Or, we could just use TravisCI to push the ARM builds to packagecloud, instead, but I'm not sure if we can consider that as an option.

Personally, I asked for a ARM image because I'm now using scaleway (which provides ARM VMs), and Varnish is one of the very few popular packages on Docker Hub that don't provide ARM images. So it would be a nice-to-have, specially with the number of IaaS supporting ARM increasing (with Amazon EC2 being one of them, for example).

**Comment by gquintard** [comment]
> hmmm..I'm not sure how I could help with a PR for this...specially that we're still dependent on a ARM support on CircleCI to work on. The instructions you given, AFAIK, would apply to a Alpine image with Varnish official sources embedded, and I'm not sure there would be a way to do that without access to a ARM machine.

`Travis` can provide that

**Comment by J0WI** [comment]
I'd like to request generic multiarch support, not just ARM.

**Comment by gquintard** [comment]
what would that entail for this repository? Building all the packages in the `Dockerfile`? (the Varnish project only produce packages for x64 and possibly arm)

**Comment by gquintard** [comment]
done!
