### ISSUE TITLE
Plans to update the Debian version of this Docker image

### ISSUE THREAD

**Issue by pacifier17** [varnish/docker-varnish#15]
Hi,
I wanted to check if you have any plans to update the Debian version of this image and re-upload it to Docker Hub? The reason is that the version of Debian (stretch) that it is based on is old and has a lot of vulnerabilities. I see that Debian has patched a lot of these vulnerabilities in their buster version.

**Comment by gquintard** [comment]
the code is there, but for some reason, I can't get the key on the server, so the build is currently faling. Once that is fixed, the official PR will be opened

**Comment by pacifier17** [comment]
Ahh thanks! Any way we can push it through soon? It would be good to patch these critical vulnerabilities quickly since this is an official Varnish image.

**Comment by gquintard** [comment]
sure, get that key https://packagecloud.io/app/varnishcache/varnish64/gpg on http://ha.pool.sks-keyservers.net/ and we are in business

**Comment by pacifier17** [comment]
I have never done this before, so I don't know where to start. What error are you facing while trying to get it on the server?

**Comment by gquintard** [comment]
none, things appear to work, and I've pushedthe key to multiple servers on the network. There's usually a delay before being able to retrieve de the key, but it's usually a few hours, not a day

**Comment by pacifier17** [comment]
So I did this (from whatever I could understand)

Ran the following command written here: https://packagecloud.io/app/varnishcache/varnish64/gpg#gpg-apt
curl -L https://packagecloud.io/varnishcache/varnish64/gpgkey

Then just copied the public key here http://ha.pool.sks-keyservers.net/ and I got this message: Key block added to key server database. New public keys added:
1 key(s) added successfully.

I am assuming that is what you have been doing?

**Comment by gquintard** [comment]
yup

**Comment by pacifier17** [comment]
Any other ideas on what else to do? I have none. :(

**Comment by gquintard** [comment]
fixed in master

**Comment by pacifier17** [comment]
Thanks! Will you push this buster image to docker hub too?

**Comment by gquintard** [comment]
https://github.com/docker-library/official-images/pull/7662
