### ISSUE TITLE
question - how to enable logs to stdout or remote log server?

### ISSUE THREAD

**Issue by loganto** [varnish/docker-varnish#20]
Hi
this container is great - I got it up and running no issues.
Im just wondering - what happens to varnish logs and if I can get them enabled?

when I run: `docker logs -f varnish` I only see minimal output:
```
k-varnish | VCL compiled.
k-varnish | 
k-varnish | Debug: Version: varnish-6.4.0 revision 13f137934ec1cf14af66baf7896311115ee35598
k-varnish | Debug: Platform: Linux,5.4.0-42-generic,x86_64,-junix,-smalloc,-sdefault,-hcritbit
k-varnish | Debug: Child (17) Started
k-varnish | Info: Child (17) said Child starts
```

but no other info on ongoing request/response or anything.

**Comment by gquintard** [comment]
Hi,

please use https://varnish-cache.org/support/ for this kind of request next time, we try to use the bug tracker is for actionable bug only.

Please have a look at https://docs.varnish-software.com/tutorials/vsl-query/ and https://info.varnish-software.com/blog/varnish-docker

Basically, run `varnishlog` or `varnishncsa` either from the same container, or from one that shares `var/lib/varnish`
