### ISSUE TITLE
ABI mismatch with 6.0.6 multi-stage build

### ISSUE THREAD

**Issue by panmruczasty** [varnish/docker-varnish#24]
Hi,
Since a few days ago, approximately the time of 6.0.7 release to the dockerhub (the first problem emerged on 13 Nov), we are experiencing ABI mismatch isues with a multi-stage build of 6.0.6. Up to the point mentioned above everything worked properly. The dockerfile and error are as follows:

```
FROM varnish:6.0.6 as builder

RUN apt-get update
RUN apt-get install -y build-essential varnish-dev libcurl4-openssl-dev python-docutils

ADD varnish-modules-0.15.0.tar.gz /tmp/modules
WORKDIR /tmp/modules/varnish-modules-0.15.0
RUN ./configure && make && make check && make install

ADD libvmod-curl-1.0.4.tar.gz /tmp/curl
WORKDIR /tmp/curl/libvmod-curl-1.0.4
RUN ./configure && make && make check && make install

ADD vmod-querystring-2.0.1.tar.gz /tmp/curl
WORKDIR /tmp/curl/vmod-querystring-2.0.1
RUN ./configure && make && make check && make install


FROM varnish:6.0.6

RUN apt-get update
RUN apt-get install -y libcurl3
COPY --from=builder /usr/lib/varnish/vmods/ /usr/lib/varnish/vmods/
ARG VARNISH_ENV
COPY docker/varnish/backends/${VARNISH_ENV}.vcl /etc/varnish/backends.vcl
COPY docker/varnish/default.vcl /etc/varnish/

CMD [ "-p", "feature=+esi_disable_xml_check" ]
```

```
portal-varnish_1  | Error:
portal-varnish_1  | Message from VCC-compiler:
portal-varnish_1  | Incompatible VMOD curl
portal-varnish_1  | 	File name: /usr/lib/varnish/vmods/libvmod_curl.so
portal-varnish_1  | 	ABI mismatch, expected <Varnish 6.0.6 29a1a8243dbef3d973aec28dc90403188c1dc8e7>, got <Varnish 6.0.7 525d371e3ea0e0c38edd7baf0f80dc226560f26e>
portal-varnish_1  | ('/etc/varnish/default.vcl' Line 3 Pos 8)
portal-varnish_1  | import curl;
portal-varnish_1  | -------####-
portal-varnish_1  | 
portal-varnish_1  | Running VCC-compiler failed, exited with 2
portal-varnish_1  | VCL compilation failed
portal-varnish-builder_bankier-portal-varnish_1 exited with code 2
```

This problem persists after switching to 6.0.7. Single-stage build of both versions is not affected, but results in a much bigger docker image of 445MB (compared to 204MB achieved with a multi-stage build).

The imports included in default.vcl are:

```
import curl;
import directors;
import std;
import querystring;
import var;
import xkey;
```

and after changing $ABI from strict to vrt for varnish-modules, libvmod-curl and vmod-querystring, directors are mentioned in the same error message, which is odd as they come precompiled with the docker image for 6.0.6.

**Comment by panmruczasty** [comment]
I think it's also worth mentioning, that the running container built from said image has the following in its logs:

```
18.11.2020 12:19:46Debug: Version: varnish-6.0.7 revision 525d371e3ea0e0c38edd7baf0f80dc226560f26e
18.11.2020 12:19:46Debug: Platform: Linux,4.15.0-121-generic,x86_64,-junix,-smalloc,-sdefault,-hcritbit
```

**Comment by gquintard** [comment]
that is a bit weird, on my machine, I get this:

```
$ docker pull varnish:6.0.6
6.0.6: Pulling from library/varnish
Digest: sha256:d28c75dbe76f5d3635ce57bfaa01daffefcb381003a09763d75cc74f8117ff49
Status: Image is up to date for varnish:6.0.6
docker.io/library/varnish:6.0.6
$ docker run varnish:6.0.6 varnishd -V
varnishd (varnish-6.0.6 revision 29a1a8243dbef3d973aec28dc90403188c1dc8e7)
Copyright (c) 2006 Verdens Gang AS
Copyright (c) 2006-2019 Varnish Software AS
```

**Comment by gquintard** [comment]
also, could you share the tarballs that you are using so we are operating with the same input?

**Comment by panmruczasty** [comment]
I've built an image locally from a dockerfile that goes like this:

```
FROM varnish:6.0.6

RUN apt-get update
RUN apt-get install -y libcurl3 build-essential varnish-dev libcurl4-openssl-dev python-docutils
ADD varnish-modules-0.15.0.tar.gz /tmp/modules
WORKDIR /tmp/modules/varnish-modules-0.15.0
RUN ./configure && make && make check && make install

ADD libvmod-curl-1.0.4.tar.gz /tmp/curl
WORKDIR /tmp/curl/libvmod-curl-1.0.4
RUN ./configure && make && make check && make install

ADD vmod-querystring-2.0.1.tar.gz /tmp/curl
WORKDIR /tmp/curl/vmod-querystring-2.0.1
RUN ./configure && make && make check && make install

COPY docker/varnish/backends/staging.vcl /etc/varnish/backends.vcl
COPY docker/varnish/default.vcl /etc/varnish/
```
This is our current single stage build. My result of docker run portal-varnish:test varnishd -V is:
```
varnishd (varnish-6.0.7 revision 525d371e3ea0e0c38edd7baf0f80dc226560f26e)
Copyright (c) 2006 Verdens Gang AS
Copyright (c) 2006-2020 Varnish Software AS
```
> also, could you share the tarballs that you are using so we are operating with the same input?

Sure thing

[libvmod-curl-1.0.4.tar.gz](https://github.com/varnish/docker-varnish/files/5562726/libvmod-curl-1.0.4.tar.gz)
[varnish-modules-0.15.0.tar.gz](https://github.com/varnish/docker-varnish/files/5562727/varnish-modules-0.15.0.tar.gz)
[vmod-querystring-2.0.1.tar.gz](https://github.com/varnish/docker-varnish/files/5562728/vmod-querystring-2.0.1.tar.gz)

**Comment by panmruczasty** [comment]
I think I found the reason of this odd behavior: installing varnish-dev forces varnish to upgrade to 6.0.7. Trying to block it with `apt-mark hold varnish` won't make the cut, as it results in unresolved dependencies.

**Comment by gquintard** [comment]
alright, so it's really just a matter of installing `varnish-dev=6.0.6-1~stretch` instead of `varnish-dev` I reckon.

I'll close this as I believe it's solved, but let me know if I'm mistaken

**Comment by panmruczasty** [comment]
I've tested the build with `varnish-dev=6.0.6-1~stretch` and can confirm it works like a charm. Thank you for your help, the issue is solved.

**Comment by gquintard** [comment]
no problem!
