### ISSUE TITLE
Memory leaks

### ISSUE THREAD

**Issue by martinsvoboda** [varnish/docker-varnish#31]
I observe memory leaks when using this image on production. Varnish slowly increases its memory usage. VARNISH_SIZE is set to 3G. After one day Varnish allocates 4 GB, but `varnishstat` returns:

```
SMA.s0.g_bytes               3.00G
SMA.Transient.g_bytes        3.47M
```

This happens both stable (varnish:6.0.7) and latest (varnish:6.6.0) releases.

Did you come across similar behaviour?

**Comment by gquintard** [comment]
Hi,

not a bug: https://varnish-cache.org/docs/trunk/users-guide/storage-backends.html#transient-storage
You can either bound the storage (add a `-s Transient=malloc,XG) to avoid it adding too much overhead
or set `shortlived` to 0 (`-p shortlived=0` in the command line) to avoid using `Transient` altogether
