### ISSUE TITLE
Document how multi-architecture images are built and published?

### ISSUE THREAD

**Issue by danielcompton** [varnish/docker-varnish#35]
I've been looking at recent multi-architecture commits (https://github.com/varnish/docker-varnish/commit/34a1562d47049ab84ab7191ef51e022a42cfe275), but I haven't been able to work out how these end up as multi-architecture Docker images. Would you be able to include a line or two in the docs about how/where these end up being built? Is it related to https://github.com/docker-library/official-images/blob/master/library/varnish?

**Comment by gquintard** [comment]
Hi,

I don't feel we should expand too much here as it is already covered by
https://github.com/docker-library/official-images#architectures-other-than-amd64

But we could possibly make clearer that this repositoriy feeds the
official-images one.

**Comment by danielcompton** [comment]
> But we could possibly make clearer that this repositoriy feeds the
official-images one.

Ah great, that's what I was after. Thanks!

**Comment by gquintard** [comment]
I'll just close this, after rereading the `README`, it gfeels fairly clear. Please reopen with suggestions if you feel strongly about this
