### ISSUE TITLE
unprivileged version

### ISSUE THREAD

**Issue by atroost** [varnish/docker-varnish#42]
When using container on Kubernetes which is running in unprivileged mode port 80 can't be used. 
This results in the following error:
```
Error: Could not get socket :80: Permission denied
(-? gives usage)

```
Would it be possible to create a image variant where the port is 8080 (>1024)?

A good example of that approach can be found here:  https://github.com/nginxinc/docker-nginx-unprivileged

**Comment by gquintard** [comment]
interestingly, port `80` doesn't seem to be privileged on the two base images we use, so we can actually just add

```
RUN chown varnish /var/lib/varnish
USER varnish
```

and things work. the only breakage would be for people using us in `FROM` and expecting to be `root`, but that's easy to spot, understand and fix I guess.

It seems like a decent solution to solve this feature request, I'll go with that and push a new image with the `7.0.1` release coming up next week. If you have remarks, opinions of want to share your current code, please pipe up before then.

**Comment by pcnoic** [comment]
> interestingly, port `80` doesn't seem to be privileged on the two base images we use, so we can actually just add
> 
> ```
> RUN chown varnish /var/lib/varnish
> USER varnish
> ```
> 
> and things work. the only breakage would be for people using us in `FROM` and expecting to be `root`, but that's easy to spot, understand and fix I guess.
> 
> It seems like a decent solution to solve this feature request, I'll go with that and push a new image with the `7.0.1` release coming up next week. If you have remarks, opinions of want to share your current code, please pipe up before then.

If I understand the release model correctly only bug & security fixes **are to** be backported into previous stable image tags as per https://github.com/varnish/docker-varnish/blob/v6.5/README.md?plain=1#L10 . Why did the unprivileged feature make it into `6.6.x`? This [commit](https://github.com/varnish/docker-varnish/commit/aaadb7ddd388f797af816f4f2a42b75325260656) is not tagged as a security fix hence the change IMO shouldn't have been backported, at least without notice.

**Comment by gquintard** [comment]
Hi,

So, there's currently no promise on the image stability, the documentation you point at describes the Varnish releases that are going to follow this pattern.

That being said, we don't enjoy breaking changes and now that we've had some experience in the `docker` space, it probably make sense to start making this promise

Originally, we started with the same template for all the versions so we could iterate faster, but we don't need that anymore, so I opened https://github.com/varnish/docker-varnish/issues/45 to track this
