### ISSUE TITLE
tmpfs with newest images

### ISSUE THREAD

**Issue by obi12341** [varnish/docker-varnish#44]
In the latest docs on hub.docker.com you are recommending to use --tmpfs /var/lib/varnish:exec which will end in a 
`varnish_1   | Error: Cannot create test-file in /var/lib/varnish/ (Permission denied)
varnish_1   | Check permissions (or delete old directory)`

This has broken our deployment and caused a downtime altough we specify `6.6` as a tag which should not contain breaking changes. 

I think this is related to commit https://github.com/varnish/docker-varnish/commit/9bbe2f325934f00ee5506c956e4883f3a8e6884e

**Comment by gquintard** [comment]
Hi @obi12341, sorry about that,

That's indeed the commit causing the issue. At the moment, all versions are updated at the same time, which led to this breaking change. I've opened https://github.com/varnish/docker-varnish/issues/45 to fix this and avoid this in the future. I will fix this formally tomorrow, but in the meantime you can start your container with `--user root` to revert to the privileged-but-working behavior.

**Comment by soleson** [comment]
This has also affected the ability for the new user `varnish` to bind to restricted ports (such as :80, and :443). Specifying `--user=root` should  work as a valid work-around in the short-term. This will likely break quite a few sites when they pull updates to their existing images (even if thery stay on the same version) until they find this issue post.

**Comment by obi12341** [comment]
true maybe revert the changes in the first step and pushing this change later on a new tag

**Comment by gquintard** [comment]
> This has also affected the ability for the new user varnish to bind to restricted ports

weird, I tested that and had no issue

> true maybe revert the changes in the first step and pushing this change later on a new tag

not easy at the moment, and `official-images` will need to merge it, but yeah, I'll try that. Hopefully people won't get madder for breaking stuff twice

**Comment by gquintard** [comment]
thanks @andrewwiik for the assist: https://github.com/docker-library/official-images/pull/11380

**Comment by gquintard** [comment]
merged, @obi12341, @soleson, can I ask you to check, once the images are available on the hub, that we are back to sanity?

**Comment by soleson** [comment]
@gquintard - Everything was fine until we attempted a production deployment where the contrib images have not already been downloaded/cached.  When it our CI process downloaded the `library/varnish:stable` image, the default user didn't have rights to bind to the port - causing the deployment to fail.

It appears reverting the changes has resolved the issue here.

**Comment by gquintard** [comment]
@soleson thanks!
