### ISSUE TITLE
xkey/ykey and varnish modules - varnish module release tag

### ISSUE THREAD

**Issue by athlan** [varnish/docker-varnish#48]
Hello @gquintard .

I've seen that you started working on varnish modules: https://github.com/varnish/docker-varnish/commit/3121f4e974de7d64ae8094c50e99a9906e39ff0c

We're keen to use xkey/ykey varnish modules to gracefully invalidate cache.

I've seen that sits in `next` release. Do you have any plans to release it as separate docker tags maybe?

**Comment by athlan** [comment]
@gquintard  I see that you released 7.1.0. Is next also available or it's related to issue #49 ?

**Comment by gquintard** [comment]
heya, `next` has `xkey` but won't be on the hub (because of the stability argument), however `7.1.0` will be on the hub AND will have `xkey`. We are just waiting for https://github.com/docker-library/official-images/pull/12047 to land. Does that answer your question and need?

**Comment by gquintard** [comment]
done
