### ISSUE TITLE
Unable to run apt-get update

### ISSUE THREAD

**Issue by ohmygod8** [varnish/docker-varnish#5]
Hi,

I am trying to install vmod modules but when I run apt-get update through `Dockerfile` it will return the following error.

> W: The repository 'https://packagecloud.io/varnishcache/varnish62/debian stretch Release' does not have a Release file.
E: Failed to fetch https://packagecloud.io/varnishcache/varnish62/debian/dists/stretch/main/binary-amd64/Packages 
E: Some index files failed to download. They have been ignored, or old ones used instead.

May I know how do I resolve this?

**Comment by jared-w** [comment]
You need to install ca-certificates and then update again.

For reference, my Dockerfile looks like this (the vmod I install is libvmod-dynamic):

```Dockerfile
FROM varnish:6.2

RUN apt-get update; \
        apt-get install -y --no-install-recommends ca-certificates gnupg curl && \
        curl -sL https://pkg.uplex.de/dpkg/uplex-varnish.gpg.key | apt-key add - && \
        echo deb https://pkg.uplex.de/dpkg/ jessie uplex-varnish > /etc/apt/sources.list.d/uplex.list && \
        apt-get update && \
        apt-get install -y --no-install-recommends libvmod-dynamic && \
        apt-get purge -y --auto-remove -o APT::AutoRemove::RecommendsImportant=false gnupg curl && \
        rm -rf /var/lib/apt/lists/*

COPY ./src/varnish/config.vcl /etc/varnish/default.vcl
```

To get apt-get update working, the only thing is required is

```Dockerfile
RUN apt-get update; apt-get install -y --no-install-recommends ca-certificates && apt-get update
```

The first semi-colon is important as it prevents docker from failing the build when the first apt-get update "fails".

---

@gquintard, A nice fix for this might be to include the single CA required for packagecloud.io to work (Amazon). This would avoid bloating up the docker container with the entire bundle of ca-certificates, but also provide a fully working apt-get install out of the box.

**Comment by ohmygod8** [comment]
Interesting.. Let me try that out. However, I still think the best way is to have the issue solved out of the box.

**Comment by gquintard** [comment]
@jared-w: I think it makes sense to have `ca-certificates` in there, it's a pretty default package. I'll consult the Docker hub team to see twhat they think of it. Thanks for having a look.

**Comment by gquintard** [comment]
should be fixed by https://github.com/docker-library/official-images/pull/6519
