### ISSUE TITLE
Why isn't there a linux/arm64/v8 docker image for 7.1.0(-alpine)?

### ISSUE THREAD

**Issue by kforsthoevel** [varnish/docker-varnish#50]
There is a linux/arm64/v8 docker image for 7.1(-alpine) but not for 7.1.0(-alpine). Is there a special reason?

**Comment by gquintard** [comment]
Hi,

I don't think that's normal: https://github.com/docker-library/official-images/blob/ac2c4bc9035aca25f144552659f814cfd60870b7/library/varnish#L10
would you mind opening an issue on `docker-library/official-images` to see what's what?

**Comment by gquintard** [comment]
thanks, reported as https://github.com/docker-library/official-images/issues/12141

**Comment by gquintard** [comment]
Thanks for confirming!
