### ISSUE TITLE
Install VMODs on the container instruction

### ISSUE THREAD

**Issue by mostafa-rz** [varnish/docker-varnish#54]
Hi guys, 
I have two questions.

1. Is there any instructions on how can I install VMODs inside my container? 
2. I tried to install headerproxy module but it doesn't work. Are the packages listed [here ](https://varnish-cache.org/vmods/) fully supported or does it depend on varnish versions?

Thanks.

**Comment by gquintard** [comment]
Hi!

Regarding installing vmods, did you have a chance to check the official
docket hub page? https://hub.docker.com/_/varnish

The vmod section should be relatively clear.

Regarding header proxy, if you check it's GitHub repo, you can see it
hasn't seen a commit in 5 years and the vmod page you linked only list him
as a 4.1 vmod. In the meantime, important APIs have changed and I assume it
won't compile on 7.1, nor even on 6.0.
Your best chance is to ping the author and see if they can update it.

Note that i have opened a PR some time ago to address inactive vmods, and
at the time, I classified headerproxy as inactive:
https://github.com/varnishcache/homepage/pull/109/files#diff-cb1037f2feb4f807ea374276fd719dc3aa8ab5a65861d4bcdbb8acf183fedf93R13

Also, while it's not official yet, there's a discord server you can use to
ask this kind of transverse questions: https://discord.gg/EuwdvbZR6d , it
maybe better/easier that github

**Comment by mostafa-rz** [comment]
Thanks a lot I get all of my answers.
