### ISSUE TITLE
Add uid to varnish user

### ISSUE THREAD

**Issue by cnwaldron** [varnish/docker-varnish#59]
I'm running into an issue with running varnish in a cluster that is very restricted. The cluster requires images to run as a non root user and if the image's user doesn't have an uid it will not allow that image to run. 
Is it possible to add uid to the varnish user in the image? 
I'm currently using the varnish:7.1.1-alpine image.

**Comment by gquintard** [comment]
Hi! Just to be sure, you are talking about explicitly setting the UID of user `varnish` right? Technically, it already has a UID (100), but I guess you can argue there's no guarantee it'll stay the same over different release.

**Comment by cnwaldron** [comment]
Correct, I know security wise they would like a user to be with an id >1000. If the Dockerfile set the user with the uid it would save a ton of additional settings required on any user needing to deploy in a cluster with these security controls.

**Comment by gquintard** [comment]
got it, we can add it for next release (march), I'll push add those changes to the `next` images so you can test that soon

**Comment by jbsky** [comment]
Hello,

Here, the user is mapped to 101:102.

You have to debug the pod to guess the id, however, I imagine with a recompile, it will change again.

Fixing the user:group id would be very useful in a kubernetes node. By overriding the command and arg, it is possible to track the flows with varnishncsa.

**Comment by gquintard** [comment]
hello you two!
I've just pushed e501191, which forces the uid/gid value when building the image. It won't be part of the official images until next march, to avoid breaking existing users' expectations, but if you are able the build the docker images in the `next/` directory and give them a try, it'd be awesome.

**Comment by jbsky** [comment]
Thank you for fixing the id, I confirm that it is ok.

**Comment by havtorr** [comment]
Hi, @gquintard 

I've noticed that after the fresh/old switchover this week, the 7.3-images no longer assign uid/gid 1000:1000 to the varnish user. 
Was this intentional?

**Comment by gquintard** [comment]
hi @havtorr , than kyou for the quick callout. It was definitely not intentional and this should be fixed soon: https://github.com/docker-library/official-images/pull/15399

sorry about that

**Comment by gquintard** [comment]
fixed, I snuck in the 7.4.1 release in the PR too, be sure to upgrade
