### ISSUE TITLE
populate.sh fails to run on Debian/Ubuntu (/bin/sh linked to dash)

### ISSUE THREAD

**Issue by stone** [varnish/docker-varnish#6]
There are some "bashisms" used, like "declare" and some bash arrays so I suggest to change the hash-bang to /bin/bash instead of /bin/sh.

**Comment by gquintard** [comment]
I'd go for just changing the shebang to `/bin/bash`, if that's ok with you?

**Comment by gquintard** [comment]
fixed by 3f19d2d
