### ISSUE TITLE
missing architectures for 7.2 images

### ISSUE THREAD

**Issue by tobybellwood** [varnish/docker-varnish#61]
There are some missing architectures for the 7.2-based images

I can't see [arm64v8](https://hub.docker.com/r/arm64v8/varnish/), [ppc64le](https://hub.docker.com/r/ppc64le/varnish/) or [s390x](https://hub.docker.com/r/s390x/varnish/)

I've pinned to 7.1 for now, but are these expected to be published?

**Comment by gquintard** [comment]
nevermind, that SHOULD do the trick, I'll wait for the hub to merge the image definition and build them to see if we're good and I'll update this ticket once we're in the clear.

again, thanks for pinging us, that's really appreciated

**Comment by tobybellwood** [comment]
Hey, no worries at all! Thanks for maintaining, letting you know there's something up is the least I can do!

**Comment by tobybellwood** [comment]
yup - looks perfect to me :1st_place_medal:
