### ISSUE TITLE
Permission denied on port 80 (-? gives usage)

### ISSUE THREAD

**Issue by stradd** [varnish/docker-varnish#65]
Helllo,

I read deb post https://github.com/varnish/docker-varnish/issues/55.

And it is there as described. varnish:6.3 - works
I need 7.1.x but can't get it to work.
The Docker runs under:
Debian 11.7
Plesk Obsidian 8.0.52 Update #3

What can I do?
Thanks very much

**Comment by gquintard** [comment]
Hi, what's your `docker` version? Older version will prevent you from using port 80 if you don't have root access.

Have you tried setting `VARNISH_HTTP_PORT` to a port higher than 1024?

Would you be able to share how the container is started and the logs/errors it creates?

**Comment by stradd** [comment]
Hello,

I'm sorry for getting in touch so late. I tested the versions.
All versions 6 of Docker are running.
The 7.0.X versions also run
From 7.1 to 7.3 I get the error message:
Error: Could not get socket :80: Permission denied (-? gives usage).

I noticed that from version 7.1 the following vartiable is added automatically:
VMOD_DEPS automake curl libtool make pkg-config python3-sphinx
this cannot be deleted. Can this be related?

Thanks very much.

**Comment by gquintard** [comment]
Hi,

Can you have a look at this please?
https://github.com/varnish/docker-varnish/issues/55

In short, either:
- upgrade your docker version
- set the VARNISH_HTTP_PORT variable to a value above 1024
- run the container as root

The VMOD_DEPS is unrelated to that situation, it's just a nice variable to
have when installing vmods.

Please let us know how it goes.

**Comment by stradd** [comment]
Hi,

Thanks very much.

I have done the points. The container will now start.
