### ISSUE TITLE
After purging the varnish cache, the image still has the same size

### ISSUE THREAD

**Issue by stradd** [varnish/docker-varnish#66]
Hi,
I used varnishadm "ban req.url ~ ." to cleared the cache.
That works too. But the image of the varnish is not getting any smaller. Only after restarting the cache does the size of the varnish image change to its initial size.

Thanks for reply.

**Comment by gquintard** [comment]
Hi,

Check https://docs.varnish-software.com/tutorials/cache-invalidation/#ban, notably the `ban lurker` parts. In short: your objects are invalid, but still there until they can be garbage-collected.

You can also check https://info.varnish-software.com/blog/best-way-to-completely-purge-a-varnish-cache for a better alternative  to your ban expression.

However, I must stress one point: you shouldn't use purging to control memory usage. You've configured Varnish to use a certain amount of memory, you shouldn't try to get it back :-)

I think this answers the question, so I'll close the issue, but you are welcome to continue the discussion here or to join us on discord (https://varnish-cache.org/support/#discord-channel)
