### ISSUE TITLE
Not able to run slash storage example. Getting error while docker build

### ISSUE THREAD

**Issue by piyush96arora1** [varnish/docker-varnish#67]
This issue tracker is meant only for actual bug, and possible feature requests. For help, please use the usual Varnish Cache help channels: https://varnish-cache.org/support/

If you encountered a bug, please include the docker  image tag you are using, as well as the steps to reproduce it.

**Comment by gquintard** [comment]
Can you share how you ran the example and what error you got please?

**Comment by gquintard** [comment]
should be fixed by 32b436f
