### ISSUE TITLE
Image 'stable' does not seem to honour env variables VARNISH_HTTP_PORT and VARNISH_PROXY_PORT

### ISSUE THREAD

**Issue by 459below** [varnish/docker-varnish#69]
When using the _stable_ image for Varnish 6 I was not able to override the standard port for HTTP, i.e. 80, with the env variable VARNISH_HTTP_PORT. This worked for me with the _fresh_ image on Varnish 7. Unfortunately I need Varnish 6 right now.

Comparing the file which is effectively the entrypoint the variable for _http_ is hardcoded. It works on 'fresh' but not for stable.

https://github.com/varnish/docker-varnish/blob/51a66e74c3a56e4def767d3ad3f6c8ad1a4addaa/stable/debian/scripts/docker-varnish-entrypoint#L11

https://github.com/varnish/docker-varnish/blob/fe621f216a08e4083e2896f8321d1dd3698e051d/fresh/debian/scripts/docker-varnish-entrypoint#L11

The documentation on https://hub.docker.com/_/varnish under **Additional configuration** -> **Listening ports (VARNISH_HTTP_PORT/VARNISH_PROXY_PORT)** did not make clear to me that these variables only work on _fresh_, i.e. Varnish 7.

To use Varnish 6, I will be working around this by overriding the entrypoint.

However, can we port functionality for env variables VARNISH_HTTP_PORT and VARNISH_PROXY_PORT to _stable_?

**Comment by gquintard** [comment]
Hi,

This is a good call out. We usually avoid to change the interface without a version change, but it probably makes sense here and should be fairly uncontroversial.

Would you like to try and open a PR?

**Comment by 459below** [comment]
OK, sure.

**Comment by 459below** [comment]
Hello,

is there something more I can do here?

**Comment by gquintard** [comment]
Pinging here was the right move, I admit I let that fall on the side. Thank you for the reminder, I'll merge the PR next week, and it'll probably be released in March with the new fresh image
