### ISSUE TITLE
What is the best way to use this image with varnishncsa?

### ISSUE THREAD

**Issue by pmendelski** [varnish/docker-varnish#7]
Hi, thanks for the image.

Could you please recommend how to generate some basic access logs using this image?

**Comment by gquintard** [comment]
Hi,

Please discuss this on the help channels: https://varnish-cache.org/support/ We try to keep the github issues for bugs.

Some thoughts on the subject: https://info.varnish-software.com/blog/varnish-docker
Basically, share the workdir as a volume, run `varnishd` in one container, `vanrishncsa` in another

**Comment by pmendelski** [comment]
Thanks
