### ISSUE TITLE
Varnish with slash

### ISSUE THREAD

**Issue by piyush96arora1** [varnish/docker-varnish#71]
I am using varnish cache with slash storage engine

This might not be an issue:
I am running varnish in a docker container with varnishd command in a custom entry point as
chown vcache. /data/varnish_storage.bin
/usr/sbin/varnishd -E /usr/lib/varnish/vmods/libvmod_slash.so -F -s fast=fellow,/data/varnish_storage.bin,1G,500M,2M -f /etc/varnish/default.vcl -a 0.0.0.0:6081
This creates a varnish_storage.bin file whose size is around 1GB
Now lets say i have to increase the storage. Is there any way i could preserve my old cache? as currently it would involve rebuild the docker as the command is in entrypoint and restart the docker. And as soon as i restart it creates a new storage file.
How could i increase storage to 2GB while preserving old storage?

**Comment by gquintard** [comment]
Hello @piyush96arora1,

There are three points to consider here here:
- how to reuse the same cache file when you change the container. For that, you need to actually have the cache file on the host disk, and mount it into the container using `--volume` (or [--mount](https://docs.docker.com/storage/volumes/#choose-the--v-or---mount-flag)))
- you really shouldn't have `varnishd` arguments backed into the entrypoint if you plan on changing them. At the very least, use environment variables to parameterize them.
- can the storage even be increase after being created? I'm not sure, that would be a question that vmod's maintainer.

I'll close this issue as I don't think there's a bug or anything to fix, but I'm happy to continue de discussion here or on `discord`

**Comment by piyush96arora1** [comment]
Thanks for prompt reply.
Actually  my run command is 
docker run --privileged -d --restart always -v /data/etc/varnish:/etc/varnish -v /data/etc/logs:/logs -v /data/etc/storage:/data --network host

So already the storage file is at the host system, but the point is the file at the start takes the space mentioned in varnishd command.
So i can preserve the storage file before a restart but there would be no point in copying the old file in the storage directory as a  restart would create new storage file with updated size.
Not getting a reply from the vmod's maintainer on this point. Could you try it at your end. It would be really helpful

**Comment by gquintard** [comment]
He's usually pretty responsive on IRC and on the `varnish-misc` mailing-list, can you try there? I don't have much more access to him than you do :-|

**Comment by piyush96arora1** [comment]
> He's usually pretty responsive on IRC and on the `varnish-misc` mailing-list, can you try there? I don't have much more access to him than you do :-|

Didn't got you: 
What is IRC?
And any specific mail which u r refering to?

**Comment by gquintard** [comment]
Here you go, that should clarify it: https://varnish-cache.org/support/index.html
